# Generated by Django 5.1.4 on 2024-12-11 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logger', '0001_initial'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='statuslog',
            index=models.Index(fields=['create_datetime'], name='logger_stat_create__cb33b0_idx'),
        ),
    ]
