# Generated by Django 5.1.4 on 2024-12-11 16:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('logger', '0002_statuslog_logger_stat_create__cb33b0_idx'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='statuslog',
            options={'ordering': ('-create_datetime',), 'verbose_name': 'System Logs', 'verbose_name_plural': 'System Logs'},
        ),
    ]
