# Generated by Django 5.1.4 on 2024-12-11 16:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('logger', '0003_alter_statuslog_options'),
    ]

    operations = [
        migrations.RenameField(
            model_name='statuslog',
            old_name='logger_name',
            new_name='app',
        ),
    ]
