# Generated by Django 5.1.4 on 2024-12-11 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logger', '0004_rename_logger_name_statuslog_app'),
    ]

    operations = [
        migrations.AddField(
            model_name='statuslog',
            name='file',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
